/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamStartRouteImport } from './routes/exam.start'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'
import { Route as ExamExamIdResultsRouteImport } from './routes/exam.$examId.results'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamStartRoute = ExamStartRouteImport.update({
  id: '/exam/start',
  path: '/exam/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdResultsRoute = ExamExamIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ExamExamIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/exam/$examId': typeof ExamExamIdRouteWithChildren
  '/exam/start': typeof ExamStartRoute
  '/exam/$examId/results': typeof ExamExamIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/exam/$examId': typeof ExamExamIdRouteWithChildren
  '/exam/start': typeof ExamStartRoute
  '/exam/$examId/results': typeof ExamExamIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/exam/$examId': typeof ExamExamIdRouteWithChildren
  '/exam/start': typeof ExamStartRoute
  '/exam/$examId/results': typeof ExamExamIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/exam/$examId'
    | '/exam/start'
    | '/exam/$examId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/exam/$examId'
    | '/exam/start'
    | '/exam/$examId/results'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/exam/$examId'
    | '/exam/start'
    | '/exam/$examId/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  ExamExamIdRoute: typeof ExamExamIdRouteWithChildren
  ExamStartRoute: typeof ExamStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/start': {
      id: '/exam/start'
      path: '/exam/start'
      fullPath: '/exam/start'
      preLoaderRoute: typeof ExamStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId/results': {
      id: '/exam/$examId/results'
      path: '/results'
      fullPath: '/exam/$examId/results'
      preLoaderRoute: typeof ExamExamIdResultsRouteImport
      parentRoute: typeof ExamExamIdRoute
    }
  }
}

interface ExamExamIdRouteChildren {
  ExamExamIdResultsRoute: typeof ExamExamIdResultsRoute
}

const ExamExamIdRouteChildren: ExamExamIdRouteChildren = {
  ExamExamIdResultsRoute: ExamExamIdResultsRoute,
}

const ExamExamIdRouteWithChildren = ExamExamIdRoute._addFileChildren(
  ExamExamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  ExamExamIdRoute: ExamExamIdRouteWithChildren,
  ExamStartRoute: ExamStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
