/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'
import { Route as ExamStartRouteImport } from './routes/exam.start'
import { Route as TestTokenRouteImport } from './routes/test.$token'
import { Route as ApiPublicPaystackVerifyRouteImport } from './routes/api/public/paystack-verify'
import { Route as ExamExamIdIndexRouteImport } from './routes/exam.$examId.index'
import { Route as ExamExamIdResultsRouteImport } from './routes/exam.$examId.results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamStartRoute = ExamStartRouteImport.update({
  id: '/exam/start',
  path: '/exam/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTokenRoute = TestTokenRouteImport.update({
  id: '/test/$token',
  path: '/test/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackVerifyRoute = ApiPublicPaystackVerifyRouteImport.update({
  id: '/api/public/paystack-verify',
  path: '/api/public/paystack-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdIndexRoute = ExamExamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamExamIdRoute,
} as any)
const ExamExamIdResultsRoute = ExamExamIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ExamExamIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/exam/$examId': typeof ExamExamIdRouteWithChildren
  '/exam/start': typeof ExamStartRoute
  '/test/$token': typeof TestTokenRoute
  '/api/public/paystack-verify': typeof ApiPublicPaystackVerifyRoute
  '/exam/$examId/results': typeof ExamExamIdResultsRoute
  '/exam/$examId/': typeof ExamExamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/exam/start': typeof ExamStartRoute
  '/test/$token': typeof TestTokenRoute
  '/api/public/paystack-verify': typeof ApiPublicPaystackVerifyRoute
  '/exam/$examId/results': typeof ExamExamIdResultsRoute
  '/exam/$examId': typeof ExamExamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/exam/$examId': typeof ExamExamIdRouteWithChildren
  '/exam/start': typeof ExamStartRoute
  '/test/$token': typeof TestTokenRoute
  '/api/public/paystack-verify': typeof ApiPublicPaystackVerifyRoute
  '/exam/$examId/results': typeof ExamExamIdResultsRoute
  '/exam/$examId/': typeof ExamExamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/payments'
    | '/exam/$examId'
    | '/exam/start'
    | '/test/$token'
    | '/api/public/paystack-verify'
    | '/exam/$examId/results'
    | '/exam/$examId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/payments'
    | '/exam/start'
    | '/test/$token'
    | '/api/public/paystack-verify'
    | '/exam/$examId/results'
    | '/exam/$examId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/payments'
    | '/exam/$examId'
    | '/exam/start'
    | '/test/$token'
    | '/api/public/paystack-verify'
    | '/exam/$examId/results'
    | '/exam/$examId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentsRoute: typeof PaymentsRoute
  ExamExamIdRoute: typeof ExamExamIdRouteWithChildren
  ExamStartRoute: typeof ExamStartRoute
  TestTokenRoute: typeof TestTokenRoute
  ApiPublicPaystackVerifyRoute: typeof ApiPublicPaystackVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/start': {
      id: '/exam/start'
      path: '/exam/start'
      fullPath: '/exam/start'
      preLoaderRoute: typeof ExamStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$token': {
      id: '/test/$token'
      path: '/test/$token'
      fullPath: '/test/$token'
      preLoaderRoute: typeof TestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-verify': {
      id: '/api/public/paystack-verify'
      path: '/api/public/paystack-verify'
      fullPath: '/api/public/paystack-verify'
      preLoaderRoute: typeof ApiPublicPaystackVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId/': {
      id: '/exam/$examId/'
      path: '/'
      fullPath: '/exam/$examId/'
      preLoaderRoute: typeof ExamExamIdIndexRouteImport
      parentRoute: typeof ExamExamIdRoute
    }
    '/exam/$examId/results': {
      id: '/exam/$examId/results'
      path: '/results'
      fullPath: '/exam/$examId/results'
      preLoaderRoute: typeof ExamExamIdResultsRouteImport
      parentRoute: typeof ExamExamIdRoute
    }
  }
}

interface ExamExamIdRouteChildren {
  ExamExamIdResultsRoute: typeof ExamExamIdResultsRoute
  ExamExamIdIndexRoute: typeof ExamExamIdIndexRoute
}

const ExamExamIdRouteChildren: ExamExamIdRouteChildren = {
  ExamExamIdResultsRoute: ExamExamIdResultsRoute,
  ExamExamIdIndexRoute: ExamExamIdIndexRoute,
}

const ExamExamIdRouteWithChildren = ExamExamIdRoute._addFileChildren(
  ExamExamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentsRoute: PaymentsRoute,
  ExamExamIdRoute: ExamExamIdRouteWithChildren,
  ExamStartRoute: ExamStartRoute,
  TestTokenRoute: TestTokenRoute,
  ApiPublicPaystackVerifyRoute: ApiPublicPaystackVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
